## Data
resolution: 0.25 # seconds
train: 'tel.csv'
test: 'validation.csv'

## Car Constants
mass: 360 # kg
wheel_radius: 0.278 # meters

# Program
debug: True

# Fit parameters
n_poly_degree: 2

## Interval Creation
prune: True
block_width: 2 # seconds
block_height_threshold: 0.5 # m/s
peak_prominence: 4
min_interval_size: 3
max_accel_held: 0.5 # seconds
max_brake_held: 0 # seconds

